language: go

dist: xenial

sudo: required

install: true

services:
  - docker

go:
  - 1.13.x

env:
  global:
    - GOARCH=$(go env GOARCH)
    - GO_FOR_RELEASE=1.13
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - RELEASE_TAG_DOWNSTREAM=1
addons:
  apt:
    update: true

install:
  - make bootstrap

before_install:
  - sudo apt-get install --yes jq
  # Download kubectl, which is a requirement for using minikube.
  #- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  # Download minikube.
  #- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.5.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  #- mkdir -p $HOME/.kube $HOME/.minikube
  #- touch $KUBECONFIG
  #- sudo minikube start --vm-driver=none --kubernetes-version=v1.14.0
  #- "sudo chown -R travis: /home/travis/.minikube/"
script:
  #- kubectl cluster-info
  # Verify kube-addon-manager.
  # kube-addon-manager is responsible for managing other kubernetes components, such as kube-dns, dashboard, storage-provisioner..
  #- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lcomponent=kube-addon-manager -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done
  - make image
  - make push
  #- ./ci/travis-ci.sh
  # If this build is running due to travis release tag, and
  # this job indicates to push the release downstream, then
  # go ahead and tag the dependent repo.
  #
  # $TRAVIS_BRANCH contains the same value as $TRAVIS_TAG.
  # Example: TRAVIS_TAG and TRAVIS_BRANCH will have v1.9.0-RC1,
  # when github release tag is v1.9.0-RC1
  #
  # OpenEBS release are triggered from release branches that are named
  # as v1.9.x or v1.9.x-hotfix or v1.9.x-custom
  #
  # The tag to release branch conversion should be handled as follows:
  # v1.9.0-RC1 => should be v1.9.x
  # v1.9.0-hotfixid => should be v1.9.x-hotfixid
  # v1.9.0 => should be v1.9.x
  # v1.9.1 => should be v1.9.x
  # v1.9.0-custom-RC1 => should be v1.9.x-custom
  # v1.9.0-custom => should be v1.9.x-custom
  # v1.9.1-custom => should be v1.9.x-custom
  # Convert the TRAVIS_TAG to the corresponding release branch.
  #
  # Allow for building forked openebs pipelines. 
  # Tag the downstream repos under current repo org. 
  - if [ -z $REPO_ORG ]; then
      REPO_ORG=$(echo "$TRAVIS_REPO_SLUG" | cut -d'/' -f1);
      export REPO_ORG;
    fi
  - if [ ! -z $TRAVIS_TAG ] && [ $RELEASE_TAG_DOWNSTREAM = 1 ] && [ "$TRAVIS_REPO_SLUG" == "$REPO_ORG/jiva-operator" ]; then
      TAG_SUFFIX=$(echo "$TRAVIS_TAG" | cut -d'-' -f2);
      if [ "$TAG_SUFFIX" == "$TRAVIS_TAG" ] || [[ $TAG_SUFFIX =~ ^RC ]]; then
        REL_SUFFIX="";
      else
        REL_SUFFIX="-$TAG_SUFFIX";
      fi;

      REL_BRANCH=$(echo $(echo "$TRAVIS_TAG" | cut -d'-' -f1 | rev | cut -d'.' -f2- | rev).x$REL_SUFFIX);

      ./build/git-release "$REPO_ORG/jiva-csi" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1;
    fi
notifications:
  email:
    recipients:
      - kiran.mova@mayadata.io
      - utkarsh.tripathi@mayadata.io
