apiVersion: openebs.io/v1alpha1
kind: JivaVolume
metadata:
  labels:
    "openebs.io/component": "jiva-operator"
  name: example-jivavolume
  namespace: openebs
spec:
  capacity: 4G
  pv: "example-jivavolume"
  replicaSC: "openebs-hostpath"
  policy:
    replicaSC: openebs-hostpath
    enableBufio: false
    autoScaling: false
    target:
      ...
    replica:
        ...
