apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: example-jivavolumepolicy
spec:
  replicaSC: openebs-hostpath
  enableBufio: false
  autoScaling: false
  target:
    ...
  replica:
    ...
status:
