apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jivavolumes.openebs.io
spec:
  group: openebs.io
  names:
    kind: JivaVolume
    listKind: JivaVolumeList
    plural: jivavolumes
    singular: jivavolume
  scope: Namespaced
  # commenting out so that we can set the status while creating CR
  #subresources:
  #  status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Status of jiva volumes (RO/RW/Unknown)
    JSONPath: .status.status
  - name: ReplicationFactor
    type: string
    description: The required no of replicas to be connected to controller
    JSONPath: .spec.replicationFactor
  - name: ReplicaCount
    type: integer
    description: The number of replicas attached to controller
    JSONPath: .status.replicaCount
  - name: Phase
    type: string
    description: Phase of JivaVolume CR
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
