apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: example-jivavolumepolicy
  namespace: openebs
spec:
  replicaSC: openebs-hostpath
  target:
    # disableMonitor: true
    replicationFactor: 1
    # auxResources:
    # tolerations:
    # resources:
    # affinity:
    # nodeSelector:
    # priorityClassName:
  # replica:
  # tolerations:
  # resources:
  # affinity:
  # nodeSelector:
  # priorityClassName:
# status:
# phase:
