apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jivavolumes.openebs.io
spec:
  group: openebs.io
  names:
    kind: JivaVolume
    listKind: JivaVolumeList
    plural: jivavolumes
    singular: jivavolume
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: JivaVolume is the Schema for the jivavolumes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: JivaVolumeSpec defines the desired state of JivaVolume
          properties:
            capacity:
              type: string
            iscsiSpec:
              properties:
                iqn:
                  type: string
                targetIP:
                  type: string
                targetPort:
                  format: int32
                  type: integer
              required:
              - iqn
              - targetIP
              - targetPort
              type: object
            mountInfo:
              properties:
                devicePath:
                  type: string
                fsType:
                  type: string
                mountPath:
                  type: string
              required:
              - devicePath
              - fsType
              - mountPath
              type: object
            policy:
              description: JivaVolumePolicySpec defines the desired state of JivaVolumePolicy
              type: object
            pv:
              type: string
          required:
          - capacity
          - iscsiSpec
          - mountInfo
          - policy
          - pv
          type: object
        status:
          description: JivaVolumeStatus defines the observed state of JivaVolume
          properties:
            phase:
              description: Phase represents the current phase of JivaVolume.
              type: string
            replicaCount:
              type: integer
            replicaStatus:
              items:
                description: ReplicaStatus stores the status of replicas
                properties:
                  address:
                    type: string
                  mode:
                    type: string
                required:
                - address
                - mode
                type: object
              type: array
            status:
              type: string
          required:
          - phase
          - replicaCount
          - replicaStatus
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
