apiVersion: v1
kind: ServiceAccount
metadata:
  name: jiva-operator
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: jiva-operator
  namespace: openebs
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - jiva-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - openebs.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jiva-operator
  namespace: openebs
subjects:
- kind: ServiceAccount
  name: jiva-operator
roleRef:
  kind: Role
  name: jiva-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiva-operator
  namespace: openebs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jiva-operator
  template:
    metadata:
      labels:
        name: jiva-operator
    spec:
      serviceAccountName: jiva-operator
      containers:
        - name: jiva-operator
          # Replace this with the built image name
          image: openebs/jiva-operator-linux_amd64:ci
          command:
          - jiva-operator
          args:
          # supported options: epoch, iso8601, millis, nano
          - "--zap-time-encoding=iso8601"
          - "--zap-sample=false"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jiva-operator"
            - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
              value: "openebs/jiva:ci"
            - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
              value: "openebs/jiva:ci"
