kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jiva-operator
  namespace: openebs
subjects:
- kind: ServiceAccount
  name: jiva-operator
roleRef:
  kind: Role
  name: jiva-operator
  apiGroup: rbac.authorization.k8s.io
