// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolume":       schema_pkg_apis_openebs_v1alpha1_JivaVolume(ref),
		"github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeSpec":   schema_pkg_apis_openebs_v1alpha1_JivaVolumeSpec(ref),
		"github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeStatus": schema_pkg_apis_openebs_v1alpha1_JivaVolumeStatus(ref),
	}
}

func schema_pkg_apis_openebs_v1alpha1_JivaVolume(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "JivaVolume is the Schema for the jivavolumes API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeSpec", "github.com/openebs/jiva-operator/pkg/apis/openebs/v1alpha1.JivaVolumeStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_openebs_v1alpha1_JivaVolumeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "JivaVolumeSpec defines the desired state of JivaVolume",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_openebs_v1alpha1_JivaVolumeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "JivaVolumeStatus defines the observed state of JivaVolume",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
