/*
Copyright 2021 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	openebsv1 "github.com/openebs/jiva-operator/pkg/apis/openebs/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJivaVolumes implements JivaVolumeInterface
type FakeJivaVolumes struct {
	Fake *FakeOpenebsV1
	ns   string
}

var jivavolumesResource = schema.GroupVersionResource{Group: "openebs.io", Version: "v1", Resource: "jivavolumes"}

var jivavolumesKind = schema.GroupVersionKind{Group: "openebs.io", Version: "v1", Kind: "JivaVolume"}

// Get takes name of the jivaVolume, and returns the corresponding jivaVolume object, and an error if there is any.
func (c *FakeJivaVolumes) Get(ctx context.Context, name string, options v1.GetOptions) (result *openebsv1.JivaVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jivavolumesResource, c.ns, name), &openebsv1.JivaVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openebsv1.JivaVolume), err
}

// List takes label and field selectors, and returns the list of JivaVolumes that match those selectors.
func (c *FakeJivaVolumes) List(ctx context.Context, opts v1.ListOptions) (result *openebsv1.JivaVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jivavolumesResource, jivavolumesKind, c.ns, opts), &openebsv1.JivaVolumeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &openebsv1.JivaVolumeList{ListMeta: obj.(*openebsv1.JivaVolumeList).ListMeta}
	for _, item := range obj.(*openebsv1.JivaVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jivaVolumes.
func (c *FakeJivaVolumes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jivavolumesResource, c.ns, opts))

}

// Create takes the representation of a jivaVolume and creates it.  Returns the server's representation of the jivaVolume, and an error, if there is any.
func (c *FakeJivaVolumes) Create(ctx context.Context, jivaVolume *openebsv1.JivaVolume, opts v1.CreateOptions) (result *openebsv1.JivaVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jivavolumesResource, c.ns, jivaVolume), &openebsv1.JivaVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openebsv1.JivaVolume), err
}

// Update takes the representation of a jivaVolume and updates it. Returns the server's representation of the jivaVolume, and an error, if there is any.
func (c *FakeJivaVolumes) Update(ctx context.Context, jivaVolume *openebsv1.JivaVolume, opts v1.UpdateOptions) (result *openebsv1.JivaVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jivavolumesResource, c.ns, jivaVolume), &openebsv1.JivaVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openebsv1.JivaVolume), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJivaVolumes) UpdateStatus(ctx context.Context, jivaVolume *openebsv1.JivaVolume, opts v1.UpdateOptions) (*openebsv1.JivaVolume, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jivavolumesResource, "status", c.ns, jivaVolume), &openebsv1.JivaVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openebsv1.JivaVolume), err
}

// Delete takes name of the jivaVolume and deletes it. Returns an error if one occurs.
func (c *FakeJivaVolumes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jivavolumesResource, c.ns, name, opts), &openebsv1.JivaVolume{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJivaVolumes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jivavolumesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &openebsv1.JivaVolumeList{})
	return err
}

// Patch applies the patch and returns the patched jivaVolume.
func (c *FakeJivaVolumes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *openebsv1.JivaVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jivavolumesResource, c.ns, name, pt, data, subresources...), &openebsv1.JivaVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openebsv1.JivaVolume), err
}
